export const CREATE = "CREATE";
export const UPDATE = "UPDATE";
export const DELETE = "DELETE";

export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_ALL_PRODUCTS = "FETCH_ALL_PRODUCTS";

export const FETCH_ALL_SLIDES = "FETCH_ALL_SLIDES";

export const FETCH_ALL_CATEGORIES = "FETCH_ALL_CATEGORIES";
export const FETCH_CATEGORY = "FETCH_CATEGORY";

export const CREATE_ORDER = "CREATE_ORDER";
export const UPDATE_ORDER = "UPDATE_ORDER";
export const DELETE_ORDER = "DELETE_ORDER";
export const FETCH_ORDER = "FETCH_ORDER";
export const FETCH_ALL_ORDERS = "FETCH_ALL_ORDERS";

export const START_LOADING = "START_LOADING";
export const END_LOADING = "END_LOADING";
